# Titolo e descrizione del sito (utili per la SEO)
title: Adam Chierici - Digital Consultant & Developer
description: >- # Il simbolo >- permette di scrivere su più righe
  Consulenza e sviluppo di applicazioni intelligenti, automazioni e soluzioni web 
  con un approccio concreto, etico e privacy-by-design.

# URL base del tuo sito (FONDAMENTALE!)
url: "https://replikate648.github.io"
baseurl: "/achierici" # Il nome del tuo repository

# Plugin per la sitemap (di solito già attivo, ma lo specifichiamo per sicurezza)
plugins:
  - jekyll-sitemap
